kumuluzee:
  name: evcharging-invoices
  version: 0.5.0
  env:
    name: dev
  server:
    http:
      port: 8082

  integrations:
    main:
      base-url: http://localhost:8080/v1
    reports:
      base-url: http://localhost:8081/v1

  secrets:
    # Temporary API key for testing (user 'microservice')
    api-key: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ5Ny1ETW5PYkFmc085ZkJVWWxvYW5mR0d6R3k4NV81NlR3RkNzNXVQWWpNIn0.eyJleHAiOjE2MzkzMTczNDgsImlhdCI6MTYzOTMxNzA0OCwianRpIjoiNjc3ZjJmYjUtYTNmNS00NmM0LTgzMzMtNDNlMDUxODQyNzBkIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo3MDAxL2F1dGgvcmVhbG1zL2V2Y2hhcmdpbmciLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiY2UyMGRiMDMtZDEwYi00ZWNiLTlhMmUtZWE2ZjZlZTJmNWZjIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZXZjaGFyZ2luZy1hcHAiLCJzZXNzaW9uX3N0YXRlIjoiNGFmZThhYjEtZGQ1ZS00OGZlLWE2MGQtMWY4MTljMmZlZWJjIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjgwODAiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtZXZjaGFyZ2luZyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjRhZmU4YWIxLWRkNWUtNDhmZS1hNjBkLTFmODE5YzJmZWViYyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoibWljcm9zZXJ2aWNlIn0.l4J-OXZiL7sjije3uInWbDm1lnxcnYUBroKuk-auLkf72FcHGEuC2gNyIjV0nAf2ace3wqSqVMvGUUI6ZCq0Jw5-mXEZFczEJwdjT8rr_o0BAxD-8ujGY03RhpNtOfkUv_zxOMgQztV3hy5-4GFE9laEF-x8RFKPDDNqyaZsmmAujiVWVm3DNMlzBJkmlGXcRECkZaR2QBZfIXwG6lgGRK6oU_8HqKYxWM819EJxO4y5xk30rA_y6CgZJaHxFNFCoVeUzU0c8UhH9IPDNNJHBuA_7Fxa0uIg9S3eRKYsiUANDiyIXB7xebSs0I4L0lNCFhytNSZ8QqBHpaDkQKQN3Q
