kumuluzee:
  name: evcharging-invoices
  version: 0.6.0
  env:
    name: dev
  server:
    http:
      port: 80

  integrations:
    main:
      base-url: http://main.prpo.erazem.eu/v1
    reports:
      base-url: http://reports.prpo.erazem.eu/v1
