version: 3.9

services:

  evcharging-main:
    build: api
    container_name: evcharging-main
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - evcharging-main
    depends_on:
      - postgres
#       - keycloak

  evcharging-reports:
    build: reports
    container_name: evcharging-reports
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - evcharging-reports
    depends_on:
      - evcharging-main

  evcharging-invoices:
    build: invoices
    container_name: evcharging-invoices
    restart: unless-stopped
    ports:
      - "8082:8082"
    networks:
      - evcharging-invoices
    depends_on:
      - evcharging-main

  postgres:
    image: docker.io/library/postgres:14.1
    container_name: evcharging-postgres
    restart: unless-stopped
    networks:
      - evcharging-main
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evcharging

#   keycloak:
#     image: docker.io/jboss/keycloak:15.0.2
#     container_name: evcharging-keycloak
#     restart: unless-stopped
#     ports:
#       - "7999:8080"
#     networks:
#       - keycloak
#     volumes:
#       - ./res/customers-realm.json:/tmp/customers-realm.json:ro
#     environment:
#       KEYCLOAK_USER: admin
#       KEYCLOAK_PASSWORD: password
#       KEYCLOAK_IMPORT: /tmp/customers-realm.json
#       KUMULUZEE_SECURITY_KEYCLOAK_JSON:
#         '{
#           "realm": "customers-realm",
#           "bearer-only": true,
#           "auth-server-url": "http://localhost:8081/auth/",
#           "ssl-required": "external",
#           "resource": "customers-api",
#           "confidential-port": 0
#         }'

networks:
  evcharging-main:
    driver: bridge
  evcharging-reports:
    driver: bridge
  evcharging-invoices:
    driver: bridge
  keycloak:
    driver: bridge
