version: 3.9

services:

  evcharging-build:
    image: evcharging-build
    build:
      context: .

  evcharging-main:
    build:
      context: api
    target: run-main
    container_name: evcharging-main
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - maven-repo:/root/.m2
    depends_on:
      - postgres
      - evcharging-build
#      - keycloak

  evcharging-reports:
    build:
      context: reports
    target: run-reports
    container_name: evcharging-reports
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - evcharging-main
      - evcharging-build

#   evcharging-invoices:
#     build:
#       context: invoices
#     target: run-invoices
#     container_name: evcharging-invoices
#     restart: unless-stopped
#     ports:
#       - "8082:8082"
#     depends_on:
#       - evcharging_main

  postgres:
    image: docker.io/library/postgres:14.1
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evcharging

#   keycloak:
#     image: docker.io/jboss/keycloak:15.0.2
#     container_name: keycloak
#     restart: unless-stopped
#     ports:
#       - "7999:8080"
#     volumes:
#       - ./res/customers-realm.json:/tmp/customers-realm.json:ro
#     environment:
#       KEYCLOAK_USER: admin
#       KEYCLOAK_PASSWORD: password
#       KEYCLOAK_IMPORT: /tmp/customers-realm.json
#       KUMULUZEE_SECURITY_KEYCLOAK_JSON:
#         '{
#           "realm": "customers-realm",
#           "bearer-only": true,
#           "auth-server-url": "http://localhost:8081/auth/",
#           "ssl-required": "external",
#           "resource": "customers-api",
#           "confidential-port": 0
#         }'

volumes:
  maven-repo: {}
