version: "3"

services:

  evcharging-main:
    build: api
    image: evcharging-main
    container_name: evcharging-main
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - evcharging-main
    depends_on:
      - postgres
      - keycloak

  evcharging-reports:
    build: reports
    image: evcharging-reports
    container_name: evcharging-reports
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - evcharging-reports
    depends_on:
      - evcharging-main

  evcharging-invoices:
    build: invoices
    image: evcharging-invoices
    container_name: evcharging-invoices
    restart: unless-stopped
    ports:
      - "8082:8082"
    networks:
      - evcharging-invoices
    depends_on:
      - evcharging-main

  postgres:
    image: docker.io/library/postgres:14.1
    container_name: evcharging-postgres
    restart: unless-stopped
    networks:
      - evcharging-main
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evcharging

  keycloak:
    image: docker.io/jboss/keycloak:15.0.2
    container_name: evcharging-keycloak
    restart: unless-stopped
    ports:
      - "7999:7999"
    networks:
      - keycloak
    volumes:
      - ./res/evcharging-keycloak.json:/tmp/evcharging-config.json:z
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: h2
      JAVA_OPTS_APPEND:
        '
          -Dkeycloak.migration.action=import
          -Dkeycloak.migration.provider=singleFile
          -Dkeycloak.migration.file=/tmp/evcharging-config.json
          -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
          -Djboss.http.port=7999
        '
      KUMULUZEE_SECURITY_KEYCLOAK_JSON:
        '{
           "realm": "evcharging",
           "bearer-only": true,
           "auth-server-url": "http://localhost:7999/auth/",
           "ssl-required": "external",
           "resource": "evcharging-api",
           "confidential-port": 0
         }'

networks:
  evcharging-main:
    driver: bridge
  evcharging-reports:
    driver: bridge
  evcharging-invoices:
    driver: bridge
  keycloak:
    driver: bridge
