version: "3"

services:

  postgres:
    image: docker.io/library/postgres:14.1
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: si.fri.prpo.skupina00.evcharging
      POSTGRES_DB: evcharging

  keycloak:
    image: docker.io/jboss/keycloak:15.0.2
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "7999:7999"
    volumes:
      - ./res/evcharging-keycloak.json:/tmp/evcharging-config.json:z
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: si.fri.prpo.skupina00.evcharging
      DB_VENDOR: h2
      JAVA_OPTS_APPEND:
        '
          -Dkeycloak.migration.action=import
          -Dkeycloak.migration.provider=singleFile
          -Dkeycloak.migration.file=/tmp/evcharging-config.json
          -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
          -Djboss.http.port=7999
        '
