apiVersion: apps/v1
kind: Deployment
metadata:
  name: evcharging-main
  labels:
    app: evcharging-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evcharging-main
  template:
    metadata:
      labels:
        app: evcharging-main
    spec:
      containers:
      - name: evcharging-main
        image: ghcr.io/erazemk/evcharging-main:0.8.1
        ports:
        - containerPort: 80
          name: server
          protocol: TCP
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: evcharging-main
  labels:
    app: evcharging-main
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: server
  selector:
    app: evcharging-main
