apiVersion: apps/v1
kind: Deployment
metadata:
  name: evcharging-invoices
  labels:
    app: evcharging-invoices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evcharging-invoices
  template:
    metadata:
      labels:
        app: evcharging-invoices
    spec:
      containers:
      - name: evcharging-invoices
        image: ghcr.io/erazemk/evcharging-invoices:latest
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP
        livensessProbe:
          httpGet:
            path: /health/live
            port: server
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: server
          initialDelaySeconds: 30
          periodSeconds: 5
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: evcharging-invoices
  labels:
    app: evcharging-invoices
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: server
  selector:
    app: evcharging-invoices
