apiVersion: apps/v1
kind: Deployment
metadata:
  name: evcharging-invoices
  labels:
    app: evcharging-invoices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evcharging-invoices
  template:
    metadata:
      labels:
        app: evcharging-invoices
    spec:
      containers:
      - name: evcharging-invoices
        image: ghcr.io/erazemk/evcharging-invoices:0.6.2
        ports:
        - containerPort: 80
          name: server
          protocol: TCP
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: evcharging-invoices
  labels:
    app: evcharging-invoices
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: server
  selector:
    app: evcharging-invoices
