kumuluzee:
  name: evcharging
  version: 0.6.0
  env:
    name: dev
  server:
    http:
      port: 8080

  integrations:
    reports:
      base-url: http://localhost:8081/v1
    invoices:
      base-url: http://localhost:8082/v1

  datasources:
    - jndi-name: jdbc/EVChargingDS
      connection-url: jdbc:postgresql://localhost:5432/evcharging
      username: postgres
      password: postgres

  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi-spec
    scan:
      packages: si.fri.prpo.skupina00.evcharging.api.v1.resources
    servers: http://localhost:8080/v1
    ui:
      mapping: /openapi
      server-auto-config:
        enabled: false

  security:
    keycloak:
      json:
        '{
           "realm": "evcharging",
           "bearer-only": true,
           "auth-server-url": "http://localhost:7999/auth/",
           "ssl-required": "external",
           "resource": "evcharging-api",
           "confidential-port": 0
         }'

  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        - jndi-name: jdbc/EVChargingDS
          type: liveness
      http-health-check:
        - connection-url: http://localhost:8080/openapi
        - connection-url: http://localhost:8081/v1/reports
        - connection-url: http://localhost:7999
