kumuluzee:
  name: evcharging
  version: 0.7.0
  env:
    name: dev
  server:
    http:
      port: 80

  datasources:
    - jndi-name: jdbc/EVChargingDS
      connection-url: jdbc:postgresql://do.erazem.eu:5432/evcharging
      username: postgres
      password: si.fri.prpo.skupina00.evcharging

  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi-spec
    scan:
      packages: si.fri.prpo.skupina00.evcharging.api.v1.resources
    servers: http://prpo.erazem.eu:80/v1
    ui:
      mapping: /openapi
      server-auto-config:
        enabled: false

  security:
    keycloak:
      json:
        '{
           "realm": "evcharging",
           "bearer-only": true,
           "auth-server-url": "http://do.erazem.eu:8080/auth/",
           "ssl-required": "none",
           "resource": "evcharging-api",
           "confidential-port": 0
         }'

  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        - jndi-name: jdbc/EVChargingDS
          type: liveness
      http-health-check:
        - connection-url: http://prpo.erazem.eu/openapi
        - connection-url: http://do.erazem.eu:8080/auth
