kumuluzee:
  name: evcharging
  version: 0.3.1
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/EVChargingDS
      connection-url: jdbc:postgresql://localhost:5432/evcharging
      username: postgres
      password: postgres
