kumuluzee:
  name: evcharging-reports
  version: 0.6.0
  env:
    name: dev
  server:
    http:
      port: 8081

  integrations:
    main:
      base-url: http://localhost:8080/v1
    invoices:
      base-url: http://localhost:8082/v1
