kumuluzee:
  name: evcharging-reports
  version: 0.6.0
  env:
    name: dev
  server:
    http:
      port: 80

  integrations:
    main:
      base-url: http://main.prpo.erazem.eu/v1
    invoices:
      base-url: http://invoices.prpo.erazem.eu/v1
